<div class='m-0 navbar nav p-2 bg-primary rounded-bottom'>
    <div class='nav-item'>
        <?if(isset($_SESSION['username'])){?>
        <a href='/index/logout' class='text-light fw-bolder fs-3'>Log Out</a>
        <?}?>
    </div>
</div>

<div id='chat' class='h-75 overflow-auto p-3'>
    <?foreach($data['chat'] as $v):?>
            <div class='w-50 ms-<? echo $v["user"]==$_SESSION['username']?"auto":"0" ?> bg-light rounded p-2 pt-1 pb-1 overflow-hidden'>
                <p class='text-success fst-italic text-end p-0 m-0'><?echo $v["user"]?></p>
                <p class='fs-3 fw-bold text-dark p-0 m-0'><?echo $v["text"]?></p>
            </div>
    <?endforeach?>
</div>
<form method="post" enctype="multipart/form-data">
    <div class='row'>
        <div class='col-3 mb-1'>
            <input type="file" name='chat_file' class='form-control'>        
        </div>
    </div>
    <div class='form-group bg-dark row' >
        <div class='col'>
            <input type='text' name='chat' class='form-control'>
        </div>
        <div class='col-1'>
            <input type='submit' class='btn btn-primary'>
        </div>
    </div>
</form>